ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'VICTORIA';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'MALYSH';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'DUBLIN';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'TOMAS';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'BRIGHTON';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'GUDZON';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'NIZZA';
ALTER TYPE "SofaModel" ADD VALUE IF NOT EXISTS 'MILAN';
